name: ci
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: python -m pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit install
          pre-commit run -a
  Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build coverage file
        run: |
          PUBLIC_KEY="$PUBLIC_KEY" PRIVATE_KEY="$PRIVATE_KEY" pytest --junitxml=pytest.xml \
          --cov-report=term-missing --cov-branch --cov-fail-under=95 \
          --cov=src tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          create-new-comment: true
